[package]
name = "tlsn-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
p256 = { version = "0.10", features = ["ecdsa", "serde"]}
webpki = { version = "0.22.0", features = ["alloc"]}
webpki-roots = "0.22.5"
x509-parser = "0.14.0"
blake3 = "1.3.3"


[dev-dependencies]
rand_chacha = "0.3"
rand = "0.8"
rand_core = "0.6"
rstest = "0.12"
hex = "0.4"
