[package]
name = "tlsn-wasm"
version = "0.1.0-alpha.5"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = true

[dependencies]
tlsn-prover.workspace = true
tlsn-verifier.workspace = true

wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-bindgen-rayon = "1.0"

getrandom = { version = "0.2", features = ["js"] }
web-time = "1.0"
ring = { version = "0.17", features = ["wasm32_unknown_unknown_js"] }
ahash = "0.8.11"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["time"] }
tracing-web = "0.1.2"

serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"

enum-try-as-inner = { version = "0.1" }

futures = "0.3"

# Use the patched ws_stream_wasm to fix the issue https://github.com/najamelan/ws_stream_wasm/issues/12#issuecomment-1711902958
ws_stream_wasm = { version = "0.7.4", git = "https://github.com/tlsnotary/ws_stream_wasm", rev = "2ed12aad9f0236e5321f577672f309920b2aef51" }

[dev-dependencies]
wasm-bindgen-test = "0.3"