[package]
name = "httpbin"
version = "0.0.0"
edition = "2021"

[dependencies]
notary-server = { path = "../../../notary-server/" }
tlsn-prover.workspace = true
tlsn-tls-core.workspace = true
webpki-roots.workspace = true
http-body-util = "0.1"
hyper = { version = "1.1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["full"] }
rustls = { version = "0.21" }
tokio = { workspace = true, features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "net",
  "io-std",
  "fs",
] }
tokio-rustls = { version = "0.24" }
tokio-util.workspace = true
serde_json = "1"

