name: wasm-build

on:
  push:
    branches:
      - dev
    tags:
      - "[v]?[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches:
      - dev

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build_and_test:
    name: Build for target wasm32-unknown-unknown
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - tlsn/tlsn-core
          - tlsn/tlsn-prover
          - components/tls/tls-client
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          toolchain: nightly

      - name: Use caching
        uses: Swatinem/rust-cache@v2.5.0
        with:
          workspaces: ${{ matrix.package }} -> ../target

      - name: "Build"
        run: cargo build --target wasm32-unknown-unknown
  build_tlsn-wasm:
    name: Build and test tlsn-wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nightly rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          toolchain: nightly
      - name: Install nightly tool-chain
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Use caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: tlsn-wasm
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: "Build and package tlsn-wasm"
        working-directory: ./tlsn/tlsn-wasm
        run: ./build.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tlsn-wasm-package
          path: tlsn-wasm/pkg/
